import Link from 'next/link';
import { AppShell } from '@/components/app-shell';

export const metadata = { title: 'Terms' };

/**
 * Terms of Use — required companion to the Privacy Policy for App Store and web.
 */
export default function TermsPage() {
  return (
    <AppShell>
      <article className="mx-auto w-full max-w-[640px] pt-4 pb-16">
        <p className="label-caps text-[var(--color-text-tertiary)]">Legal</p>
        <h1 className="display mt-1 text-[34px] leading-tight text-white">Terms of Use</h1>
        <p className="mt-2 text-[13px] text-[var(--color-text-tertiary)]">Last updated August 15, 2026</p>

        <div className="mt-8 flex flex-col gap-6 text-[15px] leading-relaxed text-[var(--color-text-secondary)]">
          <Section title="The short version">
            Be kind. Post your own fits. Don&rsquo;t harass anyone. Shop links may earn us a
            commission — never at your friends&rsquo; expense. Viola Plus is optional.
          </Section>

          <Section title="The service">
            Viola lets you upload outfit photos, see identified pieces and scores, Bloom other
            looks, save pieces into Vaults, and follow shop links to retailers. Features marked
            Plus require a paid subscription.
          </Section>

          <Section title="Accounts">
            You must provide an accurate email and keep your login secure. You are responsible for
            activity under your account. We may suspend accounts that break these terms or our
            safety rules.
          </Section>

          <Section title="Your content">
            You keep ownership of photos you post. You grant Viola a worldwide license to host,
            display, resize, and share them as needed to operate the service (including share cards
            and Open Graph previews). You represent you have the rights to post what you upload,
            and that it does not infringe anyone else&rsquo;s rights.
          </Section>

          <Section title="Acceptable use">
            No illegal content, no sexual content involving minors, no hate or credible threats, no
            spam, no scraping, no attempting to bypass paywalls or safety systems. We use automated
            filters and human review. You can report content and block users in-app.
          </Section>

          <Section title="Shopping &amp; affiliates">
            Product matches are best-effort — brands and prices can be wrong. Retail purchases are
            between you and the retailer. Outbound shop taps may be affiliate links; retailers pay
            us a commission. It does not increase the price you pay.
          </Section>

          <Section title="Viola Plus">
            Plus is billed through the Apple App Store on iOS and through Stripe on the web.
            Manage or cancel iOS subscriptions in Apple&rsquo;s subscription settings. Web
            cancellations go through the customer portal linked from Settings. Refunds follow the
            platform&rsquo;s rules.
          </Section>

          <Section title="Disclaimers">
            The service is provided “as is.” Scores and product matches are opinions generated by
            software, not professional advice. To the fullest extent allowed by law we are not
            liable for indirect or consequential damages arising from use of Viola.
          </Section>

          <Section title="Termination">
            You may delete your account anytime in Settings. We may terminate access for violations
            of these terms. Surviving sections include ownership, disclaimers, and liability limits.
          </Section>

          <Section title="Contact">
            <a className="text-[var(--color-viola-text)] hover:underline" href="mailto:help@viola.app">
              help@viola.app
            </a>
            {' · '}
            <Link href="/contact" className="text-[var(--color-viola-text)] hover:underline">
              Contact page
            </Link>
            {' · '}
            <Link href="/privacy" className="text-[var(--color-viola-text)] hover:underline">
              Privacy Policy
            </Link>
          </Section>
        </div>
      </article>
    </AppShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="display text-[22px] text-white">{title}</h2>
      <div className="mt-2">{children}</div>
    </section>
  );
}
